### ISSUE TITLE
Question Feedback

### ISSUE THREAD

**Issue by Maxianzhai** [tedhuang96/nirrt_star#1]
Hi Huang,I've found a slight problem here.
Line 74 of `generate_random_world_env_2d.py`, should `rectangle_width_range` be changed to `circle_radius_range`?

**Comment by tedhuang96** [comment]
Thanks for the feedback. You are right! This typo should have existed since the beginning of the project. I will adjust [random_2d.yml](https://github.com/tedhuang96/nirrt_star/blob/main/env_configs/random_2d.yml) and `generate_random_world_env_2d.py`, which will still be equivalent as the current setup but there will be no typos.

**Comment by tedhuang96** [comment]
Bug fixed. @https://github.com/tedhuang96/nirrt_star/commit/69e81b3597d46b696b58ed483cad56296ce6c214
